#!/usr/bin/env bash

fakeroot bash -c '
    DEB="chromium-x11_111.0.5563.147_arm64.deb"
    rm -rf tmp
    mkdir tmp
    dpkg-deb -R $DEB tmp
    patchelf --replace-needed libmali.so.1 libgbm.so.1 tmp/usr/lib/chromium/chromium-bin
    if ! grep "^Depends:" tmp/DEBIAN/control | grep "libc++1"
    then
        sed -Ei "s/^(Depends:)/\1 libc++1,/" tmp/DEBIAN/control
    fi
    dpkg-deb -b tmp ${DEB/.deb}-fixed.deb
'
